### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by daithiocrualaoich** [woofwoofinc/golden_retriever#10]
Needs:
- New MIT licence files in repository.
- MIT licence declaration.
- Dual licencing explanation in `README.md`. Primary licence is Apache-2.0 but you are permitted to use MIT if you prefer.
- Updated licence badge in `README.md`. (Remove?)
- Licence specification in `Cargo.toml`.
- `README.md` links to http://choosealicense.com/licenses/mit/ and http://choosealicense.com/licenses/apache-2.0/ or another software licence explainer site. (https://tldrlegal.com)

**Comment by passy** [comment]
👍 

For the badge, we can use [![License](https://img.shields.io/crates/l/leaf.svg)](LICENSE).
