### ISSUE TITLE
License badge is incorrect on https://github.com/woofwoofinc/golden_retriever

### ISSUE THREAD

**Issue by daithiocrualaoich** [woofwoofinc/golden_retriever#20]
Currently showing Apache 2.0 license. Should should Apache 2.0 or MIT.

<img width="643" alt="screen shot 2016-08-21 at 14 33 54" src="https://cloud.githubusercontent.com/assets/62836/17837484/5459dab2-67ac-11e6-975e-e2a98c8b3cb9.png">

**Comment by passy** [comment]
This will be because of GitHub's license API: https://api.github.com/repos/woofwoofinc/golden_retriever/license

We can fix this eventually by using a crates.io badge which then correctly uses the metadata from the toml file. We could also hard-code a correct badge until then.

**Comment by passy** [comment]
https://img.shields.io/badge/license-Apache--2.0%20OR%20MIT-blue.svg

![](https://img.shields.io/badge/license-Apache--2.0%20OR%20MIT-blue.svg)
